package compile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// MorphediffWriter handles writing compiled output to files in the target format
type MorphediffWriter struct {
	OutputPath string
	// Configuration with sensible defaults
	FileExtension      string
	UseMultiFile       bool // Default: true (one file per migration/change)
	CreateIndexFile    bool // Default: false (usually not needed for migrations)
	IndentSize         int  // Default: 2 or 4 depending on format
	AddGeneratedHeader bool // Default: true
}

// NewMorphediffWriter creates a new MorphediffWriter instance with sensible defaults
func NewMorphediffWriter(outputPath string) *MorphediffWriter {
	return &MorphediffWriter{
		OutputPath:         outputPath,
		FileExtension:      ".sql",
		UseMultiFile:       true,
		CreateIndexFile:    false, // Usually not needed for migrations
		IndentSize:         4,
		AddGeneratedHeader: true,
	}
}

// getGeneratedHeader returns a header comment for generated files
func (w *MorphediffWriter) getGeneratedHeader() string {
	return `-- Generated by Morphe Diff. DO NOT EDIT.
-- Source: Morphe Diff Document

`
}

// ensureDir creates a directory if it doesn't exist
func (w *MorphediffWriter) ensureDir(dir string) error {
	return os.MkdirAll(dir, 0755)
}

// writeFile writes content to a file with optional header
func (w *MorphediffWriter) writeFile(path string, content []byte) error {
	// Add generated header if enabled
	if w.AddGeneratedHeader {
		header := []byte(w.getGeneratedHeader())
		content = append(header, content...)
	}

	// Ensure directory exists
	dir := filepath.Dir(path)
	if err := w.ensureDir(dir); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	return os.WriteFile(path, content, 0644)
}

// WriteMigration writes a migration/change file
// TODO: Adjust naming and structure for your format
// Examples:
// - PostgreSQL: WriteMigration("001_add_user_table", content) -> 001_add_user_table.sql
// - OpenAPI: WriteMigration("add_user_endpoint", content) -> add_user_endpoint.yaml
func (w *MorphediffWriter) WriteMigration(migrationName string, content []byte) error {
	// Migration name is already in snake_case format, so just add extension
	fileName := migrationName + w.FileExtension
	filePath := filepath.Join(w.OutputPath, fileName)
	return w.writeFile(filePath, content)
}

// WriteAllMigrations writes multiple migration files
func (w *MorphediffWriter) WriteAllMigrations(migrationContents map[string][]byte) error {
	if w.UseMultiFile {
		// Write each migration to a separate file
		for migrationName, content := range migrationContents {
			if err := w.WriteMigration(migrationName, content); err != nil {
				return err
			}
		}

		// Create index file if enabled (usually not needed for migrations)
		if w.CreateIndexFile {
			return w.writeMigrationIndex(migrationContents)
		}
		return nil
	}

	// Single file mode - combine all migrations
	return w.writeSingleFile("migrations", migrationContents)
}

// writeMigrationIndex creates an index file that references all migrations
func (w *MorphediffWriter) writeMigrationIndex(contents map[string][]byte) error {
	// TODO: Implement if needed for your format
	// Examples:
	// - SQL: CREATE INDEX file listing all migrations
	// - TypeScript: Export all migration types
	return nil
}

// writeSingleFile writes all content to a single file
func (w *MorphediffWriter) writeSingleFile(fileName string, contents map[string][]byte) error {
	var combined []byte

	// Add file header
	if w.AddGeneratedHeader {
		combined = append(combined, []byte(w.getGeneratedHeader())...)
	}

	// Combine all contents
	for name, content := range contents {
		combined = append(combined, []byte(fmt.Sprintf("\n-- --- %s ---\n", name))...)
		combined = append(combined, content...)
		combined = append(combined, '\n')
	}

	// Write to single file
	filePath := filepath.Join(w.OutputPath, fileName+w.FileExtension)
	return os.WriteFile(filePath, combined, 0644)
}

// Helper function to convert type names to file names
func toFileName(typeName string) string {
	// TODO: Adjust for your format's file naming conventions
	// Examples:
	// - PostgreSQL migrations: "001_add_user_table" (keep as-is or convert to snake_case)
	// - OpenAPI: "add_user_endpoint" (kebab-case)
	// - TypeScript: "UserMigration" (PascalCase) -> "user-migration" (kebab-case)

	// Default: convert to lowercase with underscores
	var result []rune
	for i, r := range typeName {
		if i > 0 && 'A' <= r && r <= 'Z' {
			result = append(result, '_')
		}
		result = append(result, r)
	}
	return strings.ToLower(string(result))
}

