-- Generated by Morphe Diff. DO NOT EDIT.
-- Source: Morphe Diff Document

-- Add enum: UserRole
-- Classification: additive
CREATE TYPE public.user_role AS ENUM (
  'admin',
  'editor',
  'viewer'
);

