-- Generated by Morphe Diff. DO NOT EDIT.
-- Source: Morphe Diff Document

-- Entity view: UserProfile
-- Classification: additive
CREATE OR REPLACE VIEW public.user_profile_entities AS
SELECT
  contact_infos.email,
  users.id
FROM public.users
LEFT JOIN public.contact_infos
  ON users.id = contact_infos.id;

