-- Generated by Morphe Diff. DO NOT EDIT.
-- Source: Morphe Diff Document

-- Add relationship: Profile to model User
-- Classification: additive
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS profile_id INTEGER;
ALTER TABLE public.users ADD CONSTRAINT fk_users_profile FOREIGN KEY (profile_id) REFERENCES public.user_profiles(id);

