-- Generated by Morphe Diff. DO NOT EDIT.
-- Source: Morphe Diff Document

-- Add field: Email to User
-- Classification: additive
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email TEXT NOT NULL;

