-- Generated by Morphe Diff. DO NOT EDIT.
-- Source: Morphe Diff Document

-- Add model: User
CREATE TABLE IF NOT EXISTS public.users (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_created_at ON public.users(created_at);

