-- Generated by Morphe Diff. DO NOT EDIT.
-- Source: Morphe Diff Document

-- Modify field: Name in User
-- Classification: breaking
ALTER TABLE public.users ALTER COLUMN name TYPE TEXT;
ALTER TABLE public.users ALTER COLUMN name SET NOT NULL;

