-- Generated by Morphe Diff. DO NOT EDIT.
-- Source: Morphe Diff Document

-- Remove relationship: LegacyProfile from model User
-- Classification: breaking
ALTER TABLE public.users DROP CONSTRAINT IF EXISTS fk_users_legacy_profile CASCADE;
ALTER TABLE public.users DROP COLUMN IF EXISTS legacy_profile_id;

